CONFIG = {'data_path': '',
          'save_dir': '',
          'split_file': '',
          'pretrained_path': '',
          'val_ratio': 0.1,
          'test_ratio': 0.1,
          'labeled_ratio': 0.2,
          'seed': 2026,
          'epochs': 150,
          'lr': 0.0001,
          'num_workers': 4,
          'gpu': 0,
          'bs_lb': 4,
          'bs_ulb': 4,
          'bs_eval': 8,
          'phys_min': None,
          'phys_max': None}
